### ISSUE TITLE
Setting Application Parameters

### ISSUE THREAD

**Issue by mdedetrich** [kavedaa/sbt-javafx#20]
According to official oracle documentation, you can set application parameters

http://docs.oracle.com/javafx/2/deployment/packaging.htm

How would you do this using `sbt-javafx`? There doesn't appear to be any documentation for this.

**Comment by mdedetrich** [comment]
Ignore this, found the jvmargs attribute, late night :(

**Comment by mdedetrich** [comment]
Any chance we could publish the `6.2` sometime soon?

**Comment by kavedaa** [comment]
Published 0.7 today.
