### ISSUE TITLE
Scala 2.11 version is missing from maven

### ISSUE THREAD

**Issue by Sylfa** [kavedaa/sbt-javafx#21]
The scala 2.11 version is missing from maven as seen at http://search.maven.org/#browse%7C-1953409666

Including warnings from sbt just to be complete:
[warn]  module not found: no.vedaadata#sbt-javafx;0.7
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/no.vedaadata/sbt-javafx/scala_2.11/sbt_0.13/0.7/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/no.vedaadata/sbt-javafx/scala_2.11/sbt_0.13/0.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/no/vedaadata/sbt-javafx_2.11_0.13/0.7/sbt-javafx-0.7.pom

**Comment by kavedaa** [comment]
That's correct: it should be missing. The scala version of the plugin is not tied to the scala version of your project, but to the scala version of the sbt version you are running. sbt 0.13 uses scala 2.10. As far as I can tell. Not sure why it in your case is trying to use the 2.11 version. How do you include the plugin in your project? What version of sbt are you using?

**Comment by Sylfa** [comment]
plugins.sbt
>addSbtPlugin("no.vedaadata" %% "sbt-javafx" % "0.7")

sbt launcher version 0.13.7

I'm just using the version supplied on the website of sbt (and scala/etc) so it should not be any different from any other 0.13.7 version.

I do have `scalaVersion := "2.11.6"` in my build.sbt if that makes any difference?

**Comment by kavedaa** [comment]
That's odd. I'm not able to make it ask for a 2.11 version. Could you provide a complete project that demonstrates the behaviour?

**Comment by Sylfa** [comment]
Okay, I chased down what causes it. If you go into your ~/.sbt/0.13/build.sbt (or any filename.sbt) and add `scalaVersion := "2.11.7"` there you will trigger this. At least on a windows machine.

I added that there to use some of the bugfixes from 2.11.7 when I start a repl from sbt and a few other things.

**Comment by kavedaa** [comment]
I see. It seems to get too cumbersome to produce an artifact for this kind of scenario.
