### ISSUE TITLE
Publish the project to a repo?

### ISSUE THREAD

**Issue by eboto** [kavedaa/sbt-javafx#6]
Hey thanks for this great plugin.

I'm trying to develop a javafx side-project with some coworkers and the friction of having to build this project locally before using (while this project is under constant development) is making it tough.

Do you have any plan to start publishing this to a public repo?

Thanks!

**Comment by zhongwm** [comment]
Hi Kavedaa, Now it seems the whole no.vedaadata group is removed from repo1.maven.org, where I can find it?

**Comment by kavedaa** [comment]
Not sure what you're referring to. It's still there:

[info] downloading https://repo1.maven.org/maven2/no/vedaadata/sbt-javafx_2.10_0
.13/0.7/sbt-javafx-0.7.jar ...
[info]  [SUCCESSFUL ] no.vedaadata#sbt-javafx;0.7!sbt-javafx.jar (795ms)
